scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'prometheus'

  - job_name: 'app-server'

    static_configs:
      - targets: ['localhost:1111']


  - job_name: 'jmx-exporter'

    static_configs:
      - targets: ['jmx-exporter:5556']